version: "3.8"
services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:3000"
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - "5000:5000"
